import { createSnapModifier } from "@dnd-kit/modifiers";

export const gridSize = 8;
export const defaultCoordinates = {
  x: 0,
  y: 0,
};

export enum Axis {
  All,
  Vertical,
  Horizontal,
}

export enum Target {
  Self = "Self",
  Individual = "Individual",
  Party = "Party",
}

export enum AbilityType {
  Mitigation = "Mitigation",
  Healing = "Healing",
  Other = "Other",
}

export const snapToGridModifier = createSnapModifier(gridSize);

export const databaseJobs = [
  {
    id: 0,
    name: "Sage",
    skills: [
      {
        id: 1,
        name: "Holos",
        duration: 20,
        cooldown: 120,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/SGE/holos.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 5,
        name: "Krasis",
        duration: 15,
        cooldown: 60,
        target: Target.Individual,
        type: AbilityType.Healing,
        icon: "./icons/SGE/krasis.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 6,
        name: "Panhaima",
        duration: 15,
        cooldown: 120,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/SGE/panhaima.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 7,
        name: "Physis",
        duration: 15,
        cooldown: 60,
        target: Target.Party,
        type: AbilityType.Healing,
        icon: "./icons/SGE/physis_II.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 8,
        name: "Kerachole",
        duration: 15,
        cooldown: 30,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/SGE/kerachole.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 9,
        name: "Pneuma",
        duration: 0,
        cooldown: 120,
        target: Target.Party,
        type: AbilityType.Healing,
        icon: "./icons/SGE/pneuma.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 10,
        name: "Zoe",
        duration: 30,
        cooldown: 90,
        target: Target.Self,
        type: AbilityType.Other,
        icon: "./icons/SGE/zoe.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 11,
        name: "Soteria",
        duration: 15,
        cooldown: 60,
        target: Target.Self,
        type: AbilityType.Healing,
        icon: "./icons/SGE/soteria.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 12,
        name: "Haima",
        duration: 15,
        cooldown: 120,
        target: Target.Individual,
        type: AbilityType.Mitigation,
        icon: "./icons/SGE/haima.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
      {
        id: 13,
        name: "Philosophia",
        duration: 20,
        cooldown: 180,
        target: Target.Party,
        type: AbilityType.Healing,
        icon: "./icons/SGE/philosophia.png",
        color1: "#60cdb2",
        color2: "#08453f",
        active: true,
      },
    ],
    icon: "./transparent_icons/sage.png",
    active: true,
  },
  {
    id: 1,
    name: "White Mage",
    skills: [
      {
        id: 2,
        name: "Temperance",
        duration: 20,
        cooldown: 120,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/WHM_temperance.png",
        color1: "white",
        color2: "white",
        active: true,
      },
    ],
    icon: "./transparent_icons/whitemage.png",
    active: true,
  },
  {
    id: 2,
    name: "Scholar",
    skills: [
      {
        id: 3,
        name: "Expedience",
        duration: 15,
        cooldown: 120,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/SCH_expedient.png",
        color1: "white",
        color2: "white",
        active: true,
      },
    ],
    icon: "./transparent_icons/scholar.png",
    active: true,
  },
  {
    id: 3,
    name: "Astrologian",
    skills: [
      {
        id: 4,
        name: "Collective Unconscious",
        duration: 15,
        cooldown: 30,
        target: Target.Party,
        type: AbilityType.Mitigation,
        icon: "./icons/AST_collective_unconscious.png",
        color1: "white",
        color2: "white",
        active: true,
      },
    ],
    icon: "./transparent_icons/astrologian.png",
    active: true,
  },
];

export const encounter = {
  name: "The Omega Protocol",
  duration: 1200,
  nodes: [{ name: "Looper", start: 20, duration: 5 }],
};
